[31;1mCommandError: Unable to serialize database: cursor "_django_curs_140245351540544_sync_3" does not exist
[0m[{"model": "contenttypes.contenttype", "pk": 1, "fields": {"app_label": "admin", "model": "logentry"}}, {"model": "contenttypes.contenttype", "pk": 2, "fields": {"app_label": "auth", "model": "permission"}}, {"model": "contenttypes.contenttype", "pk": 3, "fields": {"app_label": "auth", "model": "group"}}, {"model": "contenttypes.contenttype", "pk": 4, "fields": {"app_label": "contenttypes", "model": "contenttype"}}, {"model": "contenttypes.contenttype", "pk": 5, "fields": {"app_label": "sessions", "model": "session"}}, {"model": "contenttypes.contenttype", "pk": 6, "fields": {"app_label": "api", "model": "category"}}, {"model": "contenttypes.contenttype", "pk": 7, "fields": {"app_label": "api", "model": "genre"}}, {"model": "contenttypes.contenttype", "pk": 8, "fields": {"app_label": "api", "model": "title"}}, {"model": "contenttypes.contenttype", "pk": 9, "fields": {"app_label": "api", "model": "review"}}, {"model": "contenttypes.contenttype", "pk": 10, "fields": {"app_label": "api", "model": "comment"}}, {"model": "contenttypes.contenttype", "pk": 11, "fields": {"app_label": "users", "model": "user"}}, {"model": "sessions.session", "pk": "32rrabt5dicrzosm1717x1uto92c28mi", "fields": {"session_data": "YTkyNjI3YzMzYTIyOTUzMmYzNmQ4N2NjMWE0MzJkZjE0MzZhZGNjYjp7Il9hdXRoX3VzZXJfaWQiOiIxIiwiX2F1dGhfdXNlcl9iYWNrZW5kIjoiZGphbmdvLmNvbnRyaWIuYXV0aC5iYWNrZW5kcy5Nb2RlbEJhY2tlbmQiLCJfYXV0aF91c2VyX2hhc2giOiI4YWIwNGE1ZjEyNzA5NmY2NjY1Y2IyMTViYTE4MDZiMzZmY2I0YmZjIn0=", "expire_date": "2021-12-09T01:37:52.745Z"}}